/* ============================================================
   NovaClip — main-process persistent store

   WHY THIS EXISTS
   ---------------
   The renderer used to keep the whole history in `localStorage`, which is
   capped at ~5 MB per origin and forces a full JSON re-serialisation of every
   clip (including base64 images) on every single write.

   This module moves persistence out of the renderer:

     kv store   -> SQLite (`better-sqlite3`) when available, otherwise an
                   atomically-written JSON document in userData.
     images     -> binary blob files / BLOB rows, referenced by id instead of
                   being inlined as base64 inside the clips document.

   Both backends expose the same small synchronous API so `electron/main.js`
   can answer `ipcMain.on('store:*')` without awaiting anything.

   The SQLite backend is *optional* and the JSON file backend is the release
   default: Windows builds must not depend on a native module. The JSON
   backend writes every acknowledged mutation to disk synchronously and
   atomically (temp file + rename + fsync), so a crash right after a write
   cannot lose it; SQLite is therefore a performance option, not a durability
   requirement. Nothing in the app depends on SQLite being present.
   ============================================================ */
'use strict';

const fs = require('fs');
const path = require('path');

const STORE_FILE = 'store.json';
const BLOB_DIR = 'blobs';
const SCHEMA_VERSION = 2;

/* ---------- small helpers ---------- */

// Blob ids are generated by the renderer; never let one escape the blob dir.
function safeName(id) {
  let n = String(id == null ? '' : id).replace(/[^a-zA-Z0-9_.-]/g, '_');
  n = n.replace(/^\.+/, '_');                 // no leading dots
  n = n.replace(/\.\./g, '__');               // no traversal sequences
  if (n.length > 120) n = n.slice(0, 120);
  return n || '_';
}

// Durable atomic write: data goes to a temp file on the same volume, is
// flushed to the OS, and only then renamed over the destination. A crash at
// any point leaves either the old file or the new file — never a torn one.
function atomicWriteFileSync(file, data) {
  const tmp = file + '.' + process.pid + '.' + Date.now() + '.tmp';
  const fd = fs.openSync(tmp, 'w', 0o600);      // clipboard data: owner-only
  try {
    fs.writeFileSync(fd, data);
    fs.fsyncSync(fd);
  } finally {
    fs.closeSync(fd);
  }
  fs.renameSync(tmp, file); // atomic on POSIX + Windows (same volume)
  // Best-effort: fsync the directory so the rename itself is durable (a power
  // loss immediately after the write cannot resurrect the old file). Opening a
  // directory read-only fails on Windows, so this is best-effort by design.
  try {
    const dfd = fs.openSync(path.dirname(file), 'r');
    try { fs.fsyncSync(dfd); } finally { fs.closeSync(dfd); }
  } catch (e) { /* ignore */ }
}

function parseDataUrl(dataUrl) {
  const m = /^data:([^;,]+)?(;base64)?,([\s\S]*)$/.exec(String(dataUrl == null ? '' : dataUrl));
  if (!m) return null;
  return { mime: m[1] || 'application/octet-stream', base64: !!m[2], payload: m[3] };
}

function dirSize(dir) {
  let total = 0;
  try {
    for (const name of fs.readdirSync(dir)) {
      try { total += fs.statSync(path.join(dir, name)).size; } catch (e) { /* ignore */ }
    }
  } catch (e) { /* missing dir */ }
  return total;
}

/* ---------- SQLite backend (optional) ---------- */

function openSqliteBackend(dir) {
  let Database = null;
  try {
    // Optional dependency — absence is normal and must not throw.
    Database = require('better-sqlite3');
  } catch (e) {
    return null;
  }
  try {
    const db = new Database(path.join(dir, 'novaclip.db'));
    db.pragma('journal_mode = WAL');
    db.exec(`
      CREATE TABLE IF NOT EXISTS kv (
        key   TEXT PRIMARY KEY,
        value TEXT NOT NULL
      );
      CREATE TABLE IF NOT EXISTS blobs (
        id   TEXT PRIMARY KEY,
        mime TEXT NOT NULL,
        data BLOB NOT NULL
      );
    `);
    const stmts = {
      all: db.prepare('SELECT key, value FROM kv'),
      get: db.prepare('SELECT value FROM kv WHERE key = ?'),
      set: db.prepare('INSERT INTO kv (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value'),
      del: db.prepare('DELETE FROM kv WHERE key = ?'),
      blobPut: db.prepare('INSERT INTO blobs (id, mime, data) VALUES (?, ?, ?) ON CONFLICT(id) DO UPDATE SET mime = excluded.mime, data = excluded.data'),
      blobGet: db.prepare('SELECT mime, data FROM blobs WHERE id = ?'),
      blobDel: db.prepare('DELETE FROM blobs WHERE id = ?'),
      kvSize: db.prepare('SELECT COALESCE(SUM(LENGTH(key) + LENGTH(value)) * 2, 0) AS n FROM kv'),
      blobSize: db.prepare('SELECT COALESCE(SUM(LENGTH(id) + LENGTH(mime) + LENGTH(data)), 0) AS n FROM blobs'),
    };

    return {
      name: 'sqlite',
      getAll() {
        const out = {};
        for (const row of stmts.all.iterate()) out[row.key] = row.value;
        return out;
      },
      get(key) {
        const row = stmts.get.get(key);
        return row ? row.value : null;
      },
      set(key, value) { stmts.set.run(key, String(value)); },
      del(key) { stmts.del.run(key); },
      putBlob(id, mime, buf) { stmts.blobPut.run(safeName(id), String(mime), buf); },
      getBlob(id) {
        const row = stmts.blobGet.get(safeName(id));
        return row ? { mime: row.mime, data: row.data } : null;
      },
      delBlob(id) { stmts.blobDel.run(safeName(id)); },
      usage() {
        return {
          kvBytes: Number(stmts.kvSize.get().n) || 0,
          blobBytes: Number(stmts.blobSize.get().n) || 0,
        };
      },
      flush() { try { db.pragma('wal_checkpoint(TRUNCATE)'); } catch (e) { /* ignore */ } },
      close() { try { db.close(); } catch (e) { /* ignore */ } },
    };
  } catch (e) {
    // Corrupt db file, locked file, ABI mismatch, … — fall back to JSON.
    return null;
  }
}

/* ---------- JSON-file backend (always available) ---------- */

function openJsonBackend(dir) {
  const file = path.join(dir, STORE_FILE);
  const blobDir = path.join(dir, BLOB_DIR);

  let doc = { version: SCHEMA_VERSION, kv: {} };
  try {
    if (fs.existsSync(file)) {
      const parsed = JSON.parse(fs.readFileSync(file, 'utf8'));
      if (parsed && typeof parsed === 'object' && parsed.kv && typeof parsed.kv === 'object') {
        doc = { version: SCHEMA_VERSION, kv: parsed.kv };
      }
    }
  } catch (e) {
    // A truncated/corrupt document must not brick the app: start empty and
    // keep the broken file around for manual recovery.
    try { fs.renameSync(file, file + '.corrupt-' + Date.now()); } catch (e2) { /* ignore */ }
    doc = { version: SCHEMA_VERSION, kv: {} };
  }

  // Remove temp files a previous run left behind when it crashed between the
  // atomic write and the rename. The document they belonged to was never
  // installed (the rename is atomic), so they are pure garbage.
  try {
    for (const name of fs.readdirSync(dir)) {
      if (/\.tmp$/.test(name)) {
        try { fs.unlinkSync(path.join(dir, name)); } catch (e) { /* ignore */ }
      }
    }
  } catch (e) { /* ignore */ }

  try { fs.mkdirSync(blobDir, { recursive: true }); } catch (e) { /* ignore */ }

  // Every kv mutation is written to disk synchronously and atomically (temp
  // file + rename + fsync). There is deliberately no debounce window: a crash
  // a moment after an acknowledged write must not lose that write. The clips
  // document stays small (image bytes live in blobs/) and the SQLite backend
  // already behaves this way, so write-through costs are acceptable.
  function writeDoc() {
    atomicWriteFileSync(file, JSON.stringify(doc));
  }

  return {
    name: 'file',
    getAll() { return Object.assign({}, doc.kv); },
    get(key) { return Object.prototype.hasOwnProperty.call(doc.kv, key) ? doc.kv[key] : null; },
    set(key, value) { doc.kv[key] = String(value); writeDoc(); },
    del(key) { delete doc.kv[key]; writeDoc(); },
    putBlob(id, mime, buf) {
      const base = path.join(blobDir, safeName(id));
      atomicWriteFileSync(base, buf);
      atomicWriteFileSync(base + '.meta', JSON.stringify({ mime: String(mime) }));
    },
    getBlob(id) {
      const base = path.join(blobDir, safeName(id));
      if (!fs.existsSync(base)) return null;
      let mime = 'application/octet-stream';
      try { mime = (JSON.parse(fs.readFileSync(base + '.meta', 'utf8')) || {}).mime || mime; } catch (e) { /* ignore */ }
      return { mime, data: fs.readFileSync(base) };
    },
    delBlob(id) {
      const base = path.join(blobDir, safeName(id));
      try { fs.unlinkSync(base); } catch (e) { /* ignore */ }
      try { fs.unlinkSync(base + '.meta'); } catch (e) { /* ignore */ }
    },
    usage() {
      let kvBytes = 0;
      for (const k of Object.keys(doc.kv)) kvBytes += (k.length + doc.kv[k].length) * 2;
      return { kvBytes, blobBytes: dirSize(blobDir) };
    },
    flush() { /* writes are synchronous — nothing is ever pending */ },
    close() { /* same */ },
  };
}

/* ---------- public factory ---------- */

/**
 * Create (or open) the persistent store rooted at `dir`.
 * @param {string} dir  absolute directory, e.g. app.getPath('userData')
 * @param {{prefer?: 'sqlite'|'file'}} [opts]
 */
function createStore(dir, opts) {
  const root = path.resolve(dir);
  try { fs.mkdirSync(root, { recursive: true }); } catch (e) { /* ignore */ }

  const prefer = (opts && opts.prefer) || 'auto';
  let backend = null;
  if (prefer !== 'file') backend = openSqliteBackend(root);
  if (!backend) backend = openJsonBackend(root);

  function putBlob(id, dataUrl) {
    const parsed = parseDataUrl(dataUrl);
    if (!parsed) throw new Error('invalid data URL');
    const buf = parsed.base64 ? Buffer.from(parsed.payload, 'base64') : Buffer.from(parsed.payload, 'utf8');
    backend.putBlob(id, parsed.mime, buf);
    return safeName(id);
  }

  function getBlob(id) {
    const found = backend.getBlob(id);
    if (!found) return null;
    const buf = Buffer.isBuffer(found.data) ? found.data : Buffer.from(found.data);
    return 'data:' + found.mime + ';base64,' + buf.toString('base64');
  }

  return {
    get backend() { return backend.name; },
    get dir() { return root; },
    getAll: () => backend.getAll(),
    get: (key) => backend.get(key),
    set: (key, value) => backend.set(key, value),
    del: (key) => backend.del(key),
    putBlob,
    getBlob,
    delBlob: (id) => backend.delBlob(id),
    usage: () => Object.assign({ backend: backend.name }, backend.usage()),
    flush: () => backend.flush(),
    close: () => backend.close(),
  };
}

module.exports = { createStore, parseDataUrl, safeName, atomicWriteFileSync };
